
name: Test-Application

on:
  workflow_call:
    inputs:
      environmentName:
        required: true
        type: string
jobs:
  deploy_environment:
    environment: azure-${{ inputs.environmentName }}
    runs-on: ubuntu-latest
    steps:
      - shell: echo hi
