name: Test-Pipeline

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8
      - name: Black
        shell: pwsh
        run: black --check .
      - name: iSort
        shell: pwsh
        run: isort --check .
      - name: Flake8
        shell: pwsh
        run: flake8 .

  Test-DEV-Environment:
    needs: Linting
    uses: ./.github/workflows/template-test-applicaiton.yml
    with:
      environmentName: dev
    secrets: inherit
  Test-TEST-Environment:
    needs: Linting
    uses: ./.github/workflows/template-test-applicaiton.yml
    with:
      environmentName: test
    secrets: inherit

