name: Resource-Deployment

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  Deploy-DEV-Environment:
    uses: ./.github/workflows/deploy-environment.yml
    with:
      environmentName: dev
    secrets: inherit
